/**
 * 
 */
package entities;

/**
 * @author miguel
 *
 */
public enum States {
    WAIT_FOR_AN_ORDER,
    PREPARING_A_COURSE,
    DISHING_THE_PORTIONS,
    DELIVERING_THE_PORTIONS,
    CLOSING_SERVICE,
    PRESENTING_THE_MENU,
    APPRAISING_SITUATION,
    TAKING_THE_ORDER,
    PLACING_THE_ORDER,
    WAITING_FOR_AN_PORTION,
    PROCESSING_THE_BILL,
    RECEIVING_PAYMENT,
    GOING_TO_THE_RESTAURANT,
    TAKING_A_SEAT_AT_THE_TABLE,
    SELECTING_THE_COURSES,
    ORGANIZING_THE_ORDER,
    CHATING_WITH_COMPANIONS,
    ENJOYING_THE_MEAL,
    PAYING_THE_BILL,
    GOING_HOME
    
}

